### PR TITLE
ompi/datatype: update COPY_DATA_DESC() to optimized datatype creation

### PR DESCRIPTION
**Pull request by ggouaillardet**
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@bosilca with this PR, ```make check``` works (at least in ```test/datatype``` directory)
can you please review it ? i suspect this fix might be an overkill

**Comment by bosilca** [comment]
@ggouaillardet the ptypes array for predefined datatype was supposed to be statically created. I might have missed something in the creation macro OPAL_DATATYPE_INIT_PTYPES_ARRAY.

**Comment by bosilca** [comment]
I just pushed a fix for this issue that correctly initialize the ptypes array for all predefined types.

**Comment by ggouaillardet** [comment]
note the bug is in the __ompi__ predefined datatypes, and __not__ in opal
the error occurs in
```c
DECLARE_MPI2_COMPOSED_BLOCK_DDT( &ompi_mpi_2int.dt, OMPI_DATATYPE_2INT, "MPI_2INT",
                                     OMPI_DATATYPE_MPI_INT,
OMPI_DATATYPE_FLAG_DATA_C | OMPI_DATATYPE_FLAG_DATA_INT );
```
this is an ompi predefined datatype that do not directly matches an opal one.

```make check``` still fails, but if you simply remove the ```memcpy``` in ```COPY_DATA_DESC()```, the test success

**Comment by ggouaillardet** [comment]
fwiw, by removing the ```memcpy()```, i can run a program such as
```c
#include <mpi.h>

int main(int argc, char *argv[]) {
    int buf[4] = {0, 1, -1, -1};
    MPI_Init(&argc, &argv);
    MPI_Sendrecv(buf, 1, MPI_2INT, 0, 0,
                 buf+2, 1, MPI_2INT, 0, 0,
                 MPI_COMM_SELF, MPI_STATUS_IGNORE);
    if (0 != buf[2] || 1 != buf[3]) MPI_Abort(MPI_COMM_WORLD, 1);
    MPI_Finalize();
    return 0;
}
```
so that might be the right fix

**Pull request closed without merging**
